# Generated by Django 5.1.4 on 2025-01-07 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_beginner_app', '0003_alter_tweet_id_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
